### ISSUE TITLE
Incorrect material for science lesson on mondays

### ISSUE THREAD

**Issue by Alvinn8** [Alvinn8/s#44]

**Comment by Bombardier-C-Kram** [comment]
@Alvinn8 Use php... PLEASE

**Comment by Bombardier-C-Kram** [comment]
:joy:

**Comment by Alvinn8** [comment]
But that’s 100 times harder to host :joy:

**Comment by Alvinn8** [comment]
Not an issue. I seam to have misread the material.

**Comment by Bombardier-C-Kram** [comment]
> But that’s 100 times harder to host joy

Nope, not really... You can use my server!!

**Comment by Bombardier-C-Kram** [comment]
I even have docker...
